environment:
  matrix:
    - nodejs_version: '4'
    - nodejs_version: '5'
    - nodejs_version: '6'
    - nodejs_version: '7'
    - nodejs_version: '8'
    - nodejs_version: '9'
    - nodejs_version: '10'
install:
  - powershell ./scripts/appveyor/prepare.ps1
  - set PATH=%APPDATA%\npm;%PATH%
  - powershell ./scripts/appveyor/install.ps1
matrix:
  fast_finish: true
build: off
shallow_clone: true
test: off
test_script:
  - echo "Disabled for now"
cache:
  - '%APPDATA%\npm-cache'
